apiVersion: v1
kind: Service
  labels:
    app: safety
  name: safety
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: safety
  sessionAffinity: None
  type: ClusterIP
